{{- $rollout := .Values.app.rollout }}
{{- $analysisTemplate := $rollout.analysisTemplate }}
{{- if and $rollout.enabled $analysisTemplate.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ default (printf "%s-analysis" (include "demo-app.fullname" .)) $analysisTemplate.nameOverride }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  metrics:
    - name: error-rate
      interval: {{ $analysisTemplate.errorRate.interval }}
      successCondition: {{ $analysisTemplate.errorRate.successCondition | quote }}
      failureCondition: {{ $analysisTemplate.errorRate.failureCondition | quote }}
      provider:
        prometheus:
          address: {{ $analysisTemplate.prometheusAddress }}
          query: |
            sum(rate(http_requests_total{app="{{ include "demo-app.name" . }}",status=~"5..",namespace="{{ .Release.Namespace }}"}[{{ $analysisTemplate.errorRate.lookbackWindow }}])) /
            sum(rate(http_requests_total{app="{{ include "demo-app.name" . }}",namespace="{{ .Release.Namespace }}"}[{{ $analysisTemplate.errorRate.lookbackWindow }}]))
{{- end }}
