{{- if and .Values.istioIngress.enabled .Values.istioIngress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "demo-app.fullname" . }}-istio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.istioIngress.tls.secretName }}
  issuerRef:
    name: {{ .Values.istioIngress.tls.issuerRef.name }}
    kind: {{ .Values.istioIngress.tls.issuerRef.kind }}
  dnsNames:
    {{- range .Values.istioIngress.hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
